export * from './cart/view'
export * from './favorite/view'
export * from './home/view'
export * from './login/view'
export * from './map/view'
export * from './profile/view'
export * from './signUp/view'
export * from './welcome/view'